# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161029223924 on 2016-11-06 17:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20161030_0205'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillSubskill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_skills', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subskill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_skills', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='sub_skills',
        ),
        migrations.AddField(
            model_name='skill',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='pictures/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subskill',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Skill'),
        ),
        migrations.AddField(
            model_name='skillsubskill',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Skill'),
        ),
        migrations.AddField(
            model_name='skillsubskill',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile'),
        ),
    ]
