# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161029223924 on 2016-11-06 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20161106_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subskill',
            name='sub_skills',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
