# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161029223924 on 2016-11-09 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20161108_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='assets/pictures/%Y/%m/%d'),
        ),
    ]
