# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161029223924 on 2016-11-11 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20161109_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='machine',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='machine',
            field=models.TextField(blank=True, null=True),
        ),
    ]
