# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20161111_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='research',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='research',
            field=models.TextField(blank=True, null=True),
        ),
    ]
