# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-04 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20161128_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('Ph.D. Student', 'Ph.D. Student'), ('post-doc', 'post-doc'), ('Assistent-professor', 'Assistent-professor'), ('Professor', 'Professor')], max_length=32),
        ),
    ]
