# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161029223924 on 2016-12-12 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20161212_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='picture_thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='assets/pictures/%Y/%m/%d'),
        ),
    ]
