# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 19:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quistion', models.CharField(blank=True, max_length=255, null=True)),
                ('answer', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_device', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('pdf_files', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d')),
                ('youtube_video', models.CharField(blank=True, max_length=255, null=True)),
                ('web_links', models.CharField(blank=True, max_length=255, null=True)),
                ('working', models.CharField(blank=True, choices=[('yes', 'yes'), ('partial', 'partial'), ('no', 'no')], max_length=32)),
                ('working_comments', models.TextField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Department')),
                ('editor', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('mentor', models.ManyToManyField(blank=True, related_name='Mentor', to=settings.AUTH_USER_MODEL)),
                ('subscriber', models.ManyToManyField(blank=True, related_name='Subscriber', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(blank=True, choices=[('Question', 'Question'), ('Problem', 'Problem')], max_length=32)),
                ('description', models.TextField()),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PageMentor+', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PageSender+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='faq',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.Machine'),
        ),
    ]
