# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161029223924 on 2016-11-01 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='booking_links',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
