# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161029223924 on 2016-11-09 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0002_machine_booking_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='machine',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.Department'),
        ),
    ]
