# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161029223924 on 2016-11-20 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0004_machine_date_of_working'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d')),
            ],
        ),
        migrations.RemoveField(
            model_name='machine',
            name='pdf_files',
        ),
        migrations.AddField(
            model_name='machine',
            name='pdf_files',
            field=models.ManyToManyField(related_name='files', to='machine.File'),
        ),
    ]
