# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161029223924 on 2016-11-20 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0005_auto_20161121_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='pdf_files',
        ),
        migrations.AddField(
            model_name='machine',
            name='pdf_files',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d'),
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
