# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161029223924 on 2016-11-21 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0007_auto_20161121_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfiles',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
