# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0008_uploadfiles_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='assets/machine-profile/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='date_of_working',
            field=models.DateField(blank=True, null=True),
        ),
    ]
