# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161029223924 on 2016-12-04 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0009_auto_20161128_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='tag',
            field=models.CharField(blank=True, choices=[('tag1', 'tag1'), ('tag2', 'tag2'), ('tag3', 'tag3'), ('tag4', 'tag4'), ('tag5', 'tag5')], max_length=32),
        ),
    ]
