# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161029223924 on 2016-12-12 05:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0010_auto_20161204_0340'),
        ('machine', '0010_auto_20161204_0936'),
    ]

    operations = [
    ]
